### ISSUE TITLE
hello, total beginner here. having problems with ACIsetSessions.

### ISSUE THREAD

**Issue by GilNimr** [dgkanatsios/AzureContainerInstancesManagement#12]
when i try to test ACIsetSessions in the portal i always get error 500.
im trying with the suggested request body format:
const acidata = [{
    resourceGroup: '',
    containerGroupName: '',
    activeSessions: 5
}];

thanks in advance!

**Comment by dgkanatsios** [comment]
You need to set values for the resourceGroup and containerGroupName variables. Empty strings will not work!

**Comment by GilNimr** [comment]
thanks for fast reply!
i have currently one container group running with 0 active sessions.
i tried it like that, but still the same problem:

const acidata = [ {
  resourceGroup : 'tree_world_try',
  "containerGroupName" : 'tree-world-containers',
  activeSessions :   8
}];

**Comment by dgkanatsios** [comment]
Can you log into the Azure portal and make sure that resourceGroup and containerGroupName are named this way? Also try to remove quotes from containersGroupName field

**Comment by GilNimr** [comment]
removed the quotes (my bad didn't notice them) and double checked the resourceGroup and containerGroupName names.

still the same error.

**Comment by dgkanatsios** [comment]
Did you use ACICreate to create the container? Did it return a 200 OK?
You can check the application insights service (you can find that inside the resource group that you deployed the Function) for detailed error log.

**Comment by GilNimr** [comment]
yes, ACICreate worked fine.
ok man i will check it out, thanks.

**Comment by GilNimr** [comment]
ok it was all just syntax issue
this worked for me:
[ {
  resourceGroup : "tree_world_try",
  containerGroupName : "tree-world-containers",
  activeSessions :   8
}]

thanks again!
